name: 'Run PM Buddy'
description: 'Runs the PM Buddy project with a given input using uv environment'
inputs:
  input:
    description: 'Input parameter to pass to the PM Buddy application'
    required: true
    default: 'Hello from pm-buddy!'
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: 'src/.python-version'

    - name: Install uv
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Sync uv environment
      shell: bash
      working-directory: src
      run: |
        uv sync

    - name: Run PM Buddy
      shell: bash
      working-directory: src
      run: |
        uv run python pm_buddy/main.py
      env:
        PM_BUDDY_INPUT: ${{ inputs.input }}
